export const weapons = [
  'Arma a distancia ligera (Arpón, arco) 1 Herida, 1 Espacio',
  'Arma cuerpo a cuerpo ligera (Daga, hacha, maza marina) 1 Herida, 1 Espacio',
  'Arma cuerpo a cuerpo ligera (Daga, hacha, maza marina) 1 Herida, 1 Espacio',
  'Arma cuerpo a cuerpo pesada (Lanza, gran hacha, martillo) 2 Heridas, 2 Espacio',
  'Arma a distancia pesada (Cañón arponero, ballesta) 2 Heridas, 2 Espacio',
  'Un orbe con un hechizo mágico aleatorio (ver Hechizos)',
];

export const armours = [
  'Ninguna',
  'Ninguna',
  'Ninguna',
  'Armadura ligera 1 Herida, 1 Espacio',
  'Armadura ligera 1 Herida, 1 Espacio',
  'Armadura pesada 2 Herida, 2 Espacio',
];

export const tools = [
  'Alga burbuja (O2)',
  'Cincel',
  'Martillo',
  'Catalejo',
  'Flauta',
  'Vendas',
  'Cuarzo radiante (Luz)',
  'Taladro',
  'Cuerda 10m',
  'Mortero',
  'Cuerno',
  'Gancho',
  'Vejiga de aire',
  'Ganzúas',
  'Cadena 2m',
  'Pizarra bioluminiscente',
  'Trompeta',
  'Alambre',
  'Pala',
  'Pico',
  'Brújula',
  'Sartén',
  'Cebo',
  'Espejo',
  'Tinta y pluma',
  'Red',
  'Feromonas',
  'Pintura de camuflaje',
  'Esposas',
  'Pedernal',
  'Sierra',
  'Tenazas',
  'Botella',
  'Silbato',
  'Antídoto ',
  'Veneno',
];

export const bodies = [
  'Atlético',
  'Fornido',
  'Fofo',
  'Imponente',
  'Larguirucho',
  'Retaco',
];

export const details = [
  'Marca',
  'Tatuajes',
  'Cicatrices',
  'Sin oreja',
  'Nariz rota',
  'Acento exótico',
];

export const hairs = [
  'Calvo',
  'Corto',
  'Largo',
  'Coleta',
  'Trenzado',
  'Peinado extraño',
];

export const virtues = [
  'Ambicioso',
  'Curioso',
  'Idealista',
  'Leal',
  'Justo',
  'Valiente',
];

export const vices = [
  'Avaricioso',
  'Vago',
  'Vengativo',
  'Arrogante',
  'Cruel',
  'Imprudente',
];

export const tragedies = [
  'Adicto',
  'Condenado',
  'Deshonrado',
  'Maldito',
  'Traicionado',
  'Arruinado',
];

export const backgrounds = [
  'Campesino',
  'Cocinero',
  'Monje',
  'Ladrón',
  'Mafioso',
  'Músico',
  'Minero',
  'Herrero',
  'Curandero',
  'Charlatán',
  'Tatuador',
  'Guardia',
  'Cantero',
  'Carpintero',
  'Mago',
  'Tahur',
  'Falsificador',
  'Soldado',
  'Marinero',
  'Herbalista',
  'Escolar',
  'Adivinador',
  'Acróbata',
  'Mercenario',
  'Cazador',
  'Alguimista',
  'Esclavo',
  'Forajido',
  'Pintor',
  'Caballero',
  'Carnicero',
  'Clérigo',
  'Mendigo',
  'Contrabandista',
  'Escultor',
  'Criador',
];

export const forms = [
  'Rayo',
  'Flecha',
  'Onda',
  'Aura',
  'Red',
  'Anillo',
  'Terreno',
  'Ola',
  'Torbellino',
  'Cascada',
  'Burbuja',
  'Muro',
  'Monolito',
  'Puerta',
  'Prisión',
  'Arma',
  'Armadura',
  'Escudo',
  'Faro',
  'Ojo',
  'Voz',
  'Canción',
  'Susurro',
  'Puño',
  'Patada',
  'Sirviente',
  'Guardián',
  'Marca',
  'Sello',
  'Garra',
  'Mordisco',
  'Alas',
  'Tentáculo',
  'Bestia',
  'Planta',
  'Vehículo',
];

export const elements = [
  'Energía',
  'Agua',
  'Aire',
  'Tierra',
  'Fuego',
  'Relámpago',
  'Niebla',
  'Hielo',
  'Sal',
  'Piedra',
  'Arena',
  'Ceniza',
  'Sombra',
  'Luz',
  'Sonido',
  'Vida',
  'Muerte',
  'Sangre',
  'Hueso',
  'Aceite',
  'Ácido',
  'Veneno',
  'Enfermedad',
  'Tiempo',
  'Saber',
  'Premonición',
  'Recuerdo',
  'Alma',
  'Astro',
  'Odio',
  'Amor',
  'Ira',
  'Calma',
  'Codicia',
  'Terror',
  'Dolor',
];

export const powers = [
  'Silencioso',
  'Ruidosa',
  'Acelerante',
  'Ralentizante',
  'Iridiscente',
  'Ocultador',
  'Ilusoria',
  'Irrompible',
  'Flotante',
  'Hundidora',
  'Ardiente',
  'Congelante',
  'Reductor',
  'Expansor',
  'Negador',
  'Infeccioso',
  'Intoxicante',
  'Drenador',
  'Controlador',
  'Transformador',
  'Confuso',
  'Enlazante',
  'Regeneradora',
  'Paralizante',
  'Desterrador',
  'Vengadora',
  'Humeante',
  'Encantadora',
  'Adormecedor',
  'Tranquilizador',
  'Sensibilizador',
  'Invisible',
  'Debilitante',
  'Empoderante',
  'Cegador',
  'Aterrador',
];
